version: 0.0
os: windows
files:
  - source: studentify.war 
    destination: /opt/tomcat/webapps/
    file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: deploy-script/appstop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: deploy-script/beforeinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy-script/appstart.sh
      timeout: 300
      runas: root