name: Test 

on:
  push:
    branches: [ "main" ] # para hacerlo manual 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # esto es para que en github action salga un boton para hacerlo a mano.

jobs: # esto son los que, build no tiene nombre puede ser otro
  test:

    runs-on: ubuntu-22.04
    permissions: # esto son los permisos que tiene esta ejecución sobre lo de github.
      contents: read

    steps: # esto es el que y se ejecuta de manera secuencias.
    - uses: actions/checkout@v4 #esto es que va a ejecutar una acción, la primera es la check, y copia el código de repo y lo mete en el contenedor
    - name: Set up JDK 21 # segunda acción montamos un JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' # esta acción tiene estos parametro que se marca con with
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle   # configura graddle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Change Gradle Weapper permissions
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew test   # aqui compila
